### ISSUE TITLE
Magento 2.3 - TinyMCE 4 Toolbar / Text Color Tool Missing

### ISSUE THREAD

**Issue by MagefanCustomer** [magefan/module-wysiwyg-advanced#30]

**Comment by magefan** [comment]
<p>In Magento 2.3 and greater, Magento team has changed WYSIWYG editor,&nbsp;instead of&nbsp;<strong>TinyMCE 3</strong> Magento started use&nbsp;<strong>TinyMCE 4</strong>.</p>
<p>On the picture below, you can see Magento 2.0-2.2&nbsp;<strong>TinyMCE 3</strong>&nbsp; editor:</p>
<p><img src="https://cm.magefan.com/wysiwyg/Blog/TinyMCE-3-Editor-Magento2-min.png" alt="TinyMCE 3 Magento 2 Editor" width="931" height="336"></p>
<p>Default Magento&nbsp;<strong>TinyMCE 4</strong>&nbsp;editor does not include a lot of tools for example text color or text background and this can be inconvenient&nbsp;for the content manager.</p>
<p><img src="https://cm.magefan.com/wysiwyg/Blog/default-magento2.2-wysiwyg-min.png" alt="Magento 2 TinyMCE 4" width="931" height="283"></p>
<p><strong>You can easily solve this issue,&nbsp;</strong>extend the WYSIWYG tool and have more options by installing&nbsp;<a title="Download magefan/module-wysiwyg-advanced" href="https://github.com/magefan/module-wysiwyg-advanced" target="_blank" rel="nofollow noopener">magefan/module-wysiwyg-advanced</a>&nbsp;free Magento 2 extension.</p>
<p>After the extension installation, new options will be available for you, e.g.:&nbsp;&nbsp;text color, HTML code, undo-redo, style select, font size selector, forecolor background color, strikethrough. Example:&nbsp;</p>
<p><img src="https://cm.magefan.com/wysiwyg/Blog/TinyMCE4-magento2-v2.png" alt="Extended Magento 2 WYSIWYG editor" width="931" height="357"></p>
<p>This extension also fix the issue with additional empty &lt;p&gt; tag (e.g. &lt;p&gt;&amp;nbsp;&lt;/p&gt;) and missing &lt;style&gt; tag in the editor.</p>
<p>To install&nbsp;<strong>magefan/module-wysiwyg-advanced</strong>, please run the CLI commands in your Magento 2 root directory:</p>
<pre>composer require magefan/module-wysiwyg-advanced<br>php bin/magento setup:upgrade<br>php bin/magento setup:di:compile<br>php bin/magento setup:static-content:deploy -f</pre>
<p>P.S.: We want to thank&nbsp;<a href="https://magento.stackexchange.com/users/77224/mike-dubs" target="_blank" rel="nofollow noopener">Mike Dubs</a> for sharing his solution at <a href="https://magento.stackexchange.com/questions/263745/magento-2-3-tinymce4-toolbar-and-plugin-configuration#answer-263891" target="_self" rel="nofollow noopener">StackExchange</a>. Based on Mike's suggestion there was created a magefan/module-wysiwyg-advanced package.</p>
